# Generated by Django 4.0.5 on 2022-12-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteria',
            name='id_repor',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
